/*
 * Copyright (c) 2010 Brigham Young University
 * 
 * This file is part of the BYU RapidSmith Tools.
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *     http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License..
 * 
 */
package edu.byu.ece.rapidSmith.gui;

import java.util.HashMap;

import io.qt.core.Qt;
import io.qt.gui.QColor;

import edu.byu.ece.rapidSmith.device.Tile;
import edu.byu.ece.rapidSmith.device.TileType;

/**
 * This class is simply a suggested coloring of tile types for displaying
 * a grid of tiles.
 * @author Chris Lavin
 * Created on: Jan 22, 2011
 */
public class TileColors {
	
	private static HashMap<TileType, QColor> tileColors;

	/**
	 * Gets a suggested color based on the tile's tileType. 
	 * @param tile The tile for which to get the color suggestion.
	 * @return A suggested color, or null if none exists.
	 */
	public static QColor getSuggestedTileColor(Tile tile){
		return tileColors.get(tile.getType());
	}
	
	static{
		tileColors = new HashMap<TileType, QColor>();
		QColor cyan = new QColor(Qt.GlobalColor.cyan);
		QColor black = new QColor(Qt.GlobalColor.black);
		QColor darkBlue = new QColor(Qt.GlobalColor.darkBlue);
		QColor darkCyan = new QColor(Qt.GlobalColor.darkCyan);
		QColor darkGray = new QColor(Qt.GlobalColor.darkGray);
		QColor darkGreen = new QColor(Qt.GlobalColor.darkGreen);
		QColor darkMagenta = new QColor(Qt.GlobalColor.darkMagenta);
		QColor darkRed = new QColor(Qt.GlobalColor.darkRed);
		QColor darkYellow = new QColor(Qt.GlobalColor.darkYellow);
		
		tileColors.put(TileType.BBSTERM, darkGray);
		tileColors.put(TileType.BBTERM, darkGray);
		tileColors.put(TileType.BCLKTERM012, darkGray);
		tileColors.put(TileType.BCLKTERM123, darkGray);
		tileColors.put(TileType.BCLKTERM2, darkGray);
		tileColors.put(TileType.BCLKTERM3, darkGray);
		tileColors.put(TileType.BGCLKVTERM, darkGray);
		tileColors.put(TileType.BGIGABIT, black);
		tileColors.put(TileType.BGIGABIT10, black);
		tileColors.put(TileType.BGIGABIT10_INT0, black);
		tileColors.put(TileType.BGIGABIT10_INT1, black);
		tileColors.put(TileType.BGIGABIT10_INT2, black);
		tileColors.put(TileType.BGIGABIT10_INT3, black);
		tileColors.put(TileType.BGIGABIT10_INT4, black);
		tileColors.put(TileType.BGIGABIT10_INT5, black);
		tileColors.put(TileType.BGIGABIT10_INT6, black);
		tileColors.put(TileType.BGIGABIT10_INT7, black);
		tileColors.put(TileType.BGIGABIT10_INT8, black);
		tileColors.put(TileType.BGIGABIT10_INT_TERM, black);
		tileColors.put(TileType.BGIGABIT10_IOI_TERM, black);
		tileColors.put(TileType.BGIGABIT10_TERM, black);
		tileColors.put(TileType.BGIGABIT_INT0, black);
		tileColors.put(TileType.BGIGABIT_INT1, black);
		tileColors.put(TileType.BGIGABIT_INT2, black);
		tileColors.put(TileType.BGIGABIT_INT3, black);
		tileColors.put(TileType.BGIGABIT_INT4, black);
		tileColors.put(TileType.BGIGABIT_INT_TERM, black);
		tileColors.put(TileType.BGIGABIT_IOI_TERM, black);
		tileColors.put(TileType.BGIGABIT_TERM, black);
		tileColors.put(TileType.BIBUFS, darkGreen);
		tileColors.put(TileType.BIOB, darkGreen);
		tileColors.put(TileType.BIOB_SINGLE, darkGreen);
		tileColors.put(TileType.BIOB_SINGLE_ALT, darkGreen);
		tileColors.put(TileType.BIOIB, darkGreen);
		tileColors.put(TileType.BIOIS, darkGreen);
		tileColors.put(TileType.BIOI_INNER, darkGreen);
		tileColors.put(TileType.BIOI_INNER_UNUSED, darkGreen);
		tileColors.put(TileType.BIOI_OUTER, darkGreen);
		tileColors.put(TileType.BIOI_OUTER_UNUSED, darkGreen);
		tileColors.put(TileType.BL_DLLIOB, darkGreen);
		tileColors.put(TileType.BOT, darkGreen);
		tileColors.put(TileType.BPPC_X0Y0_INT, black);
		tileColors.put(TileType.BPPC_X1Y0_INT, black);
		tileColors.put(TileType.BRAM, darkMagenta);
		tileColors.put(TileType.BRAM0, darkMagenta);
		tileColors.put(TileType.BRAM0_SMALL, darkMagenta);
		tileColors.put(TileType.BRAM0_SMALL_BOT, darkMagenta);
		tileColors.put(TileType.BRAM1, darkMagenta);
		tileColors.put(TileType.BRAM1_SMALL, darkMagenta);
		tileColors.put(TileType.BRAM2, darkMagenta);
		tileColors.put(TileType.BRAM2_DN_GCLKH_FEEDTHRU, darkMagenta);
		tileColors.put(TileType.BRAM2_DN_GCLKH_FEEDTHRUA, darkMagenta);
		tileColors.put(TileType.BRAM2_FEEDTHRU, darkMagenta);
		tileColors.put(TileType.BRAM2_FEEDTHRUH, darkMagenta);
		tileColors.put(TileType.BRAM2_FEEDTHRUH_50A, darkMagenta);
		tileColors.put(TileType.BRAM2_FEEDTHRU_BRK, darkMagenta);
		tileColors.put(TileType.BRAM2_GCLKH_FEEDTHRU, darkMagenta);
		tileColors.put(TileType.BRAM2_GCLKH_FEEDTHRUA, darkMagenta);
		tileColors.put(TileType.BRAM2_MID_GCLKH_FEEDTHRU, darkMagenta);
		tileColors.put(TileType.BRAM2_MID_GCLKH_FEEDTHRUA, darkMagenta);
		tileColors.put(TileType.BRAM2_SMALL, darkMagenta);
		tileColors.put(TileType.BRAM2_UP_GCLKH_FEEDTHRU, darkMagenta);
		tileColors.put(TileType.BRAM2_UP_GCLKH_FEEDTHRUA, darkMagenta);
		tileColors.put(TileType.BRAM3, darkMagenta);
		tileColors.put(TileType.BRAM3_SMALL, darkMagenta);
		tileColors.put(TileType.BRAM3_SMALL_BRK, darkMagenta);
		tileColors.put(TileType.BRAM3_SMALL_TOP, darkMagenta);
		tileColors.put(TileType.BRAMS2E_BOT_NOGCLK, darkMagenta);
		tileColors.put(TileType.BRAMS2E_CLKH, darkMagenta);
		tileColors.put(TileType.BRAMS2E_TOP_NOGCLK, darkMagenta);
		tileColors.put(TileType.BRAMSITE, darkMagenta);
		tileColors.put(TileType.BRAMSITE2, darkMagenta);
		tileColors.put(TileType.BRAMSITE2H, darkMagenta);
		tileColors.put(TileType.BRAMSITE2H_50A, darkMagenta);
		tileColors.put(TileType.BRAMSITE2_3M, darkMagenta);
		tileColors.put(TileType.BRAMSITE2_3M_BOT, darkMagenta);
		tileColors.put(TileType.BRAMSITE2_3M_BRK, darkMagenta);
		tileColors.put(TileType.BRAMSITE2_3M_TOP, darkMagenta);
		tileColors.put(TileType.BRAMSITE2_BOT, darkMagenta);
		tileColors.put(TileType.BRAMSITE2_BRK, darkMagenta);
		tileColors.put(TileType.BRAMSITE2_DN_GCLKH, darkMagenta);
		tileColors.put(TileType.BRAMSITE2_DUMMY, darkMagenta);
		tileColors.put(TileType.BRAMSITE2_GCLKH, darkMagenta);
		tileColors.put(TileType.BRAMSITE2_MID_GCLKH, darkMagenta);
		tileColors.put(TileType.BRAMSITE2_TOP, darkMagenta);
		tileColors.put(TileType.BRAMSITE2_UP_GCLKH, darkMagenta);
		tileColors.put(TileType.BRAMSITEH, darkMagenta);
		tileColors.put(TileType.BRAMSITE_GCLKH, darkMagenta);
		tileColors.put(TileType.BRAMSITE_IOIS, darkMagenta);
		tileColors.put(TileType.BRAMSITE_PPC_X0Y0_INT, darkMagenta);
		tileColors.put(TileType.BRAMSITE_PPC_X1Y0_INT, darkMagenta);
		tileColors.put(TileType.BRAMSITE_PTERMB, darkMagenta);
		tileColors.put(TileType.BRAMSITE_PTERMT, darkMagenta);
		tileColors.put(TileType.BRAMSITE_RPPC_X0Y0_INT, darkMagenta);
		tileColors.put(TileType.BRAMSITE_RPPC_X1Y0_INT, darkMagenta);
		tileColors.put(TileType.BRAM_BOT, darkMagenta);
		tileColors.put(TileType.BRAM_BOT_BTERM_L, darkMagenta);
		tileColors.put(TileType.BRAM_BOT_BTERM_R, darkMagenta);
		tileColors.put(TileType.BRAM_BOT_GCLK, darkMagenta);
		tileColors.put(TileType.BRAM_BOT_NOGCLK, darkMagenta);
		tileColors.put(TileType.BRAM_CLKH, darkRed);
		tileColors.put(TileType.BRAM_HCLK_FEEDTHRU, cyan);
		tileColors.put(TileType.BRAM_HCLK_FEEDTHRU_FOLD, cyan);
		tileColors.put(TileType.BRAM_HCLK_FEEDTHRU_INTER, cyan);
		tileColors.put(TileType.BRAM_HCLK_FEEDTHRU_INTER_FOLD, cyan);
		tileColors.put(TileType.BRAM_INTER_BTERM, darkMagenta);
		tileColors.put(TileType.BRAM_INTER_TTERM, darkMagenta);
		tileColors.put(TileType.BRAM_INT_INTERFACE_BOT, darkMagenta);
		tileColors.put(TileType.BRAM_INT_INTERFACE_TOP, darkMagenta);
		tileColors.put(TileType.BRAM_IOIS, darkMagenta);
		tileColors.put(TileType.BRAM_IOIS_NODCM, darkMagenta);
		tileColors.put(TileType.BRAM_REGH_FEEDTHRU, darkMagenta);
		tileColors.put(TileType.BRAM_REGH_FEEDTHRU_INTER, darkMagenta);
		tileColors.put(TileType.BRAM_TOP, darkMagenta);
		tileColors.put(TileType.BRAM_TOP_GCLK, darkMagenta);
		tileColors.put(TileType.BRAM_TOP_NOGCLK, darkMagenta);
		tileColors.put(TileType.BRAM_TOP_TTERM_L, darkMagenta);
		tileColors.put(TileType.BRAM_TOP_TTERM_R, darkMagenta);
		tileColors.put(TileType.BRKH, darkBlue);
		tileColors.put(TileType.BRKH_BRAM, darkBlue);
		tileColors.put(TileType.BRKH_BUFGCTRL, darkBlue);
		tileColors.put(TileType.BRKH_B_TERM_INT, darkBlue);
		tileColors.put(TileType.BRKH_CLB, darkBlue);
		tileColors.put(TileType.BRKH_CMT, darkBlue);
		tileColors.put(TileType.BRKH_DCM, darkBlue);
		tileColors.put(TileType.BRKH_DSP, darkBlue);
		tileColors.put(TileType.BRKH_DUMMY, darkBlue);
		tileColors.put(TileType.BRKH_GT3, darkBlue);
		tileColors.put(TileType.BRKH_GTH, darkBlue);
		tileColors.put(TileType.BRKH_GTX, darkBlue);
		tileColors.put(TileType.BRKH_GTX_EMP, darkBlue);
		tileColors.put(TileType.BRKH_GTX_L, darkBlue);
		tileColors.put(TileType.BRKH_GTX_LEFT, darkBlue);
		tileColors.put(TileType.BRKH_INT, darkBlue);
		tileColors.put(TileType.BRKH_INT_INTERFACE, darkBlue);
		tileColors.put(TileType.BRKH_IOB, darkBlue);
		tileColors.put(TileType.BRKH_IOI, darkBlue);
		tileColors.put(TileType.BRKH_IOIS, darkBlue);
		tileColors.put(TileType.BRKH_MGT, darkBlue);
		tileColors.put(TileType.BRKH_MGT11CLK_L, darkBlue);
		tileColors.put(TileType.BRKH_MGT11CLK_R, darkBlue);
		tileColors.put(TileType.BRKH_MGT_R, darkBlue);
		tileColors.put(TileType.BRKH_PPC, darkBlue);
		tileColors.put(TileType.BRKH_T_TERM_INT, darkBlue);
		tileColors.put(TileType.BRKH_VBRK, darkBlue);
		tileColors.put(TileType.BR_DLLIOB, darkGreen);
		tileColors.put(TileType.BTERM, darkGray);
		tileColors.put(TileType.BTERM010, darkGray);
		tileColors.put(TileType.BTERM012, darkGray);
		tileColors.put(TileType.BTERM1, darkGray);
		tileColors.put(TileType.BTERM123, darkGray);
		tileColors.put(TileType.BTERM1_MACC, darkGray);
		tileColors.put(TileType.BTERM2, darkGray);
		tileColors.put(TileType.BTERM2CLK, darkGray);
		tileColors.put(TileType.BTERM3, darkGray);
		tileColors.put(TileType.BTERM323, darkGray);
		tileColors.put(TileType.BTERM4, darkGray);
		tileColors.put(TileType.BTERM4CLK, darkGray);
		tileColors.put(TileType.BTERM4_BRAM2, darkGray);
		tileColors.put(TileType.BTERMCLK, darkGray);
		tileColors.put(TileType.BTERMCLKA, darkGray);
		tileColors.put(TileType.BTERMCLKB, darkGray);
		tileColors.put(TileType.BTTERM, darkGray);
		tileColors.put(TileType.B_TERM_DSP, darkGray);
		tileColors.put(TileType.B_TERM_INT, darkGray);
		tileColors.put(TileType.B_TERM_INT_D, darkGray);
		tileColors.put(TileType.CCM, black);
		tileColors.put(TileType.CENTER, new QColor(Qt.GlobalColor.blue));
		tileColors.put(TileType.CENTER_SMALL, new QColor(Qt.GlobalColor.blue));
		tileColors.put(TileType.CENTER_SMALL_BRK, new QColor(Qt.GlobalColor.blue));
		tileColors.put(TileType.CENTER_SPACE1, new QColor(Qt.GlobalColor.blue));
		tileColors.put(TileType.CENTER_SPACE2, new QColor(Qt.GlobalColor.blue));
		tileColors.put(TileType.CENTER_SPACE_HCLK1, new QColor(Qt.GlobalColor.blue));
		tileColors.put(TileType.CENTER_SPACE_HCLK2, new QColor(Qt.GlobalColor.blue));
		tileColors.put(TileType.CFG_CENTER, darkBlue);
		tileColors.put(TileType.CFG_CENTER_0, darkBlue);
		tileColors.put(TileType.CFG_CENTER_1, darkBlue);
		tileColors.put(TileType.CFG_CENTER_2, darkBlue);
		tileColors.put(TileType.CFG_CENTER_3, darkBlue);
		tileColors.put(TileType.CFG_HCLK_INTERFACE, cyan);
		tileColors.put(TileType.CFG_PPC_DL_BUFS, darkBlue);
		tileColors.put(TileType.CFG_PPC_R_VBRK, darkBlue);
		tileColors.put(TileType.CFG_PPC_VBRK, darkBlue);
		tileColors.put(TileType.CFG_VBRK, darkBlue);
		tileColors.put(TileType.CFG_VBRK_FRAME, darkBlue);
		tileColors.put(TileType.CIOB, darkGreen);
		tileColors.put(TileType.CLB, new QColor(Qt.GlobalColor.blue));
		tileColors.put(TileType.CLBLL, new QColor(Qt.GlobalColor.blue));
		tileColors.put(TileType.CLBLM, new QColor(Qt.GlobalColor.blue));
		tileColors.put(TileType.CLB_BUFFER, new QColor(Qt.GlobalColor.blue));
		tileColors.put(TileType.CLB_EMP_BTERM, new QColor(Qt.GlobalColor.blue));
		tileColors.put(TileType.CLB_INT_BTERM, new QColor(Qt.GlobalColor.blue));
		tileColors.put(TileType.CLEXL, new QColor(Qt.GlobalColor.blue));
		tileColors.put(TileType.CLEXL_DUMMY, new QColor(Qt.GlobalColor.blue));
		tileColors.put(TileType.CLEXM, new QColor(Qt.GlobalColor.blue));
		tileColors.put(TileType.CLEXM_DUMMY, new QColor(Qt.GlobalColor.blue));
		tileColors.put(TileType.CLKB, darkRed);
		tileColors.put(TileType.CLKB_2DLL, darkRed);
		tileColors.put(TileType.CLKB_4DLL, darkRed);
		tileColors.put(TileType.CLKB_LL, darkRed);
		tileColors.put(TileType.CLKC, darkRed);
		tileColors.put(TileType.CLKC_50A, darkRed);
		tileColors.put(TileType.CLKC_LL, darkRed);
		tileColors.put(TileType.CLKH, darkRed);
		tileColors.put(TileType.CLKH_50A, darkRed);
		tileColors.put(TileType.CLKH_DCM_CC, darkRed);
		tileColors.put(TileType.CLKH_DCM_FT, darkRed);
		tileColors.put(TileType.CLKH_DCM_LL, darkRed);
		tileColors.put(TileType.CLKH_LL, darkRed);
		tileColors.put(TileType.CLKL, darkRed);
		tileColors.put(TileType.CLKLH_DCM, darkRed);
		tileColors.put(TileType.CLKLH_DCM_LL, darkRed);
		tileColors.put(TileType.CLKL_IOIS, darkRed);
		tileColors.put(TileType.CLKL_IOIS_50A, darkRed);
		tileColors.put(TileType.CLKL_IOIS_LL, darkRed);
		tileColors.put(TileType.CLKR, darkRed);
		tileColors.put(TileType.CLKRH_DCM, darkRed);
		tileColors.put(TileType.CLKRH_DCM_LL, darkRed);
		tileColors.put(TileType.CLKR_IOIS, darkRed);
		tileColors.put(TileType.CLKR_IOIS_50A, darkRed);
		tileColors.put(TileType.CLKR_IOIS_LL, darkRed);
		tileColors.put(TileType.CLKT, darkRed);
		tileColors.put(TileType.CLKT_2DLL, darkRed);
		tileColors.put(TileType.CLKT_4DLL, darkRed);
		tileColors.put(TileType.CLKT_LL, darkRed);
		tileColors.put(TileType.CLKV, darkRed);
		tileColors.put(TileType.CLKVC, darkRed);
		tileColors.put(TileType.CLKVCU1, darkRed);
		tileColors.put(TileType.CLKVCU2, darkRed);
		tileColors.put(TileType.CLKVC_LL, darkRed);
		tileColors.put(TileType.CLKVD1, darkRed);
		tileColors.put(TileType.CLKVD2, darkRed);
		tileColors.put(TileType.CLKVU1, darkRed);
		tileColors.put(TileType.CLKVU2, darkRed);
		tileColors.put(TileType.CLKV_DCM, darkRed);
		tileColors.put(TileType.CLKV_DCM_B, darkRed);
		tileColors.put(TileType.CLKV_DCM_LL, darkRed);
		tileColors.put(TileType.CLKV_DCM_T, darkRed);
		tileColors.put(TileType.CLKV_LL, darkRed);
		tileColors.put(TileType.CLKV_MC, darkRed);
		tileColors.put(TileType.CLK_BUFGCTRL_B, darkRed);
		tileColors.put(TileType.CLK_BUFGCTRL_T, darkRed);
		tileColors.put(TileType.CLK_BUFGMUX, darkRed);
		tileColors.put(TileType.CLK_CMT_BOT, darkRed);
		tileColors.put(TileType.CLK_CMT_BOT_MGT, darkRed);
		tileColors.put(TileType.CLK_CMT_TOP, darkRed);
		tileColors.put(TileType.CLK_CMT_TOP_MGT, darkRed);
		tileColors.put(TileType.CLK_HROW, darkRed);
		tileColors.put(TileType.CLK_HROW_MGT, darkRed);
		tileColors.put(TileType.CLK_IOB_B, darkRed);
		tileColors.put(TileType.CLK_IOB_T, darkRed);
		tileColors.put(TileType.CLK_MGT_BOT, darkRed);
		tileColors.put(TileType.CLK_MGT_BOT_MGT, darkRed);
		tileColors.put(TileType.CLK_MGT_TOP, darkRed);
		tileColors.put(TileType.CLK_MGT_TOP_MGT, darkRed);
		tileColors.put(TileType.CLK_TERM_B, darkRed);
		tileColors.put(TileType.CLK_TERM_BOT, darkRed);
		tileColors.put(TileType.CLK_TERM_T, darkRed);
		tileColors.put(TileType.CLK_TERM_TOP, darkRed);
		tileColors.put(TileType.CMT_BOT, darkRed);
		tileColors.put(TileType.CMT_BUFG_BOT, darkRed);
		tileColors.put(TileType.CMT_BUFG_TOP, darkRed);
		tileColors.put(TileType.CMT_CAP, darkRed);
		tileColors.put(TileType.CMT_DCM2_BOT, darkRed);
		tileColors.put(TileType.CMT_DCM2_TOP, darkRed);
		tileColors.put(TileType.CMT_DCM_BOT, darkRed);
		tileColors.put(TileType.CMT_DCM_TOP, darkRed);
		tileColors.put(TileType.CMT_HCLK_BOT25, darkRed);
		tileColors.put(TileType.CMT_PLL1_BOT, darkRed);
		tileColors.put(TileType.CMT_PLL2_BOT, darkRed);
		tileColors.put(TileType.CMT_PLL2_TOP, darkRed);
		tileColors.put(TileType.CMT_PLL3_BOT, darkRed);
		tileColors.put(TileType.CMT_PLL3_TOP, darkRed);
		tileColors.put(TileType.CMT_PLL_BOT, darkRed);
		tileColors.put(TileType.CMT_PLL_TOP, darkRed);
		tileColors.put(TileType.CMT_PMVA, darkRed);
		tileColors.put(TileType.CMT_PMVA_BELOW, darkRed);
		tileColors.put(TileType.CMT_PMVB, darkRed);
		tileColors.put(TileType.CMT_PMVB_BUF_ABOVE, darkRed);
		tileColors.put(TileType.CMT_PMVB_BUF_BELOW, darkRed);
		tileColors.put(TileType.CMT_TOP, darkRed);
		tileColors.put(TileType.CNR_BR_BTERM, darkGray);
		tileColors.put(TileType.CNR_BTERM, darkGray);
		tileColors.put(TileType.CNR_LBTERM, darkGray);
		tileColors.put(TileType.CNR_LTERM, darkGray);
		tileColors.put(TileType.CNR_LTTERM, darkGray);
		tileColors.put(TileType.CNR_RBTERM, darkGray);
		tileColors.put(TileType.CNR_RTERM, darkGray);
		tileColors.put(TileType.CNR_RTTERM, darkGray);
		tileColors.put(TileType.CNR_TL_LTERM, darkGray);
		tileColors.put(TileType.CNR_TR_RTERM, darkGray);
		tileColors.put(TileType.CNR_TR_TTERM, darkGray);
		tileColors.put(TileType.CNR_TTERM, darkGray);
		tileColors.put(TileType.COB_NO_TERM, darkGray);
		tileColors.put(TileType.COB_TERM_B, darkGray);
		tileColors.put(TileType.COB_TERM_T, darkGray);
		tileColors.put(TileType.DCM, darkRed);
		tileColors.put(TileType.DCMAUX_BL_CENTER, darkRed);
		tileColors.put(TileType.DCMAUX_TL_CENTER, darkRed);
		tileColors.put(TileType.DCM_BGAP, darkRed);
		tileColors.put(TileType.DCM_BL_CENTER, darkRed);
		tileColors.put(TileType.DCM_BL_TERM, darkRed);
		tileColors.put(TileType.DCM_BOT, darkRed);
		tileColors.put(TileType.DCM_BR_CENTER, darkRed);
		tileColors.put(TileType.DCM_H_BL_CENTER, darkRed);
		tileColors.put(TileType.DCM_H_BR_CENTER, darkRed);
		tileColors.put(TileType.DCM_H_BR_TERM, darkRed);
		tileColors.put(TileType.DCM_H_TL_CENTER, darkRed);
		tileColors.put(TileType.DCM_H_TR_CENTER, darkRed);
		tileColors.put(TileType.DCM_H_TR_TERM, darkRed);
		tileColors.put(TileType.DCM_SPLY, darkRed);
		tileColors.put(TileType.DCM_TERM, darkRed);
		tileColors.put(TileType.DCM_TERM_MULT, darkRed);
		tileColors.put(TileType.DCM_TERM_NOMEM, darkRed);
		tileColors.put(TileType.DCM_TL_CENTER, darkRed);
		tileColors.put(TileType.DCM_TL_TERM, darkRed);
		tileColors.put(TileType.DCM_TR_CENTER, darkRed);
		tileColors.put(TileType.DSP, darkCyan);
		tileColors.put(TileType.DSP_BOT_BTERM_L, darkCyan);
		tileColors.put(TileType.DSP_BOT_BTERM_R, darkCyan);
		tileColors.put(TileType.DSP_CLB_HCLK_FEEDTHRU, darkCyan);
		tileColors.put(TileType.DSP_CLB_HCLK_FEEDTHRU_FOLD, darkCyan);
		tileColors.put(TileType.DSP_EMP_BOT, darkCyan);
		tileColors.put(TileType.DSP_EMP_TEMP, darkCyan);
		tileColors.put(TileType.DSP_EMP_TOP, darkCyan);
		tileColors.put(TileType.DSP_HCLK_FEEDTHRU_TOP, cyan);
		tileColors.put(TileType.DSP_HCLK_GCLK_FOLD, cyan);
		tileColors.put(TileType.DSP_HCLK_GCLK_NOFOLD, cyan);
		tileColors.put(TileType.DSP_INTER_TTERM, darkCyan);
		tileColors.put(TileType.DSP_INT_BTERM, darkCyan);
		tileColors.put(TileType.DSP_INT_EMP_BOT, darkCyan);
		tileColors.put(TileType.DSP_INT_EMP_TOP, darkCyan);
		tileColors.put(TileType.DSP_INT_HCLK_FEEDTHRU, cyan);
		tileColors.put(TileType.DSP_INT_HCLK_FEEDTHRU_FOLD, darkCyan);
		tileColors.put(TileType.DSP_INT_TTERM, darkCyan);
		tileColors.put(TileType.DSP_TOP_TTERM_L, darkCyan);
		tileColors.put(TileType.DSP_TOP_TTERM_R, darkCyan);
		tileColors.put(TileType.EMAC, black);
		tileColors.put(TileType.EMAC_DUMMY, black);
		tileColors.put(TileType.EMAC_INT_INTERFACE, black);
		tileColors.put(TileType.EMPTY, QColor.fromRgb(240, 141, 45));
		tileColors.put(TileType.EMPTY0X2, QColor.fromRgb(240, 141, 45));
		tileColors.put(TileType.EMPTY0X22, QColor.fromRgb(240, 141, 45));
		tileColors.put(TileType.EMPTY0X3, QColor.fromRgb(240, 141, 45));
		tileColors.put(TileType.EMPTY0X4, QColor.fromRgb(240, 141, 45));
		tileColors.put(TileType.EMPTY0X64, QColor.fromRgb(240, 141, 45));
		tileColors.put(TileType.EMPTY16X2, QColor.fromRgb(240, 141, 45));
		tileColors.put(TileType.EMPTY16X4, QColor.fromRgb(240, 141, 45));
		tileColors.put(TileType.EMPTY64X76, QColor.fromRgb(240, 141, 45));
		tileColors.put(TileType.EMPTY80X22, QColor.fromRgb(240, 141, 45));
		tileColors.put(TileType.EMPTY80X64, QColor.fromRgb(240, 141, 45));
		tileColors.put(TileType.EMPTY_BIOI, QColor.fromRgb(240, 141, 45));
		tileColors.put(TileType.EMPTY_BRAM, black);
		tileColors.put(TileType.EMPTY_BRAM_LL, QColor.fromRgb(240, 141, 45));
		tileColors.put(TileType.EMPTY_BRKH, QColor.fromRgb(240, 141, 45));
		tileColors.put(TileType.EMPTY_BTERM, QColor.fromRgb(240, 141, 45));
		tileColors.put(TileType.EMPTY_CCM, QColor.fromRgb(240, 141, 45));
		tileColors.put(TileType.EMPTY_CFG_CENTER, QColor.fromRgb(240, 141, 45));
		tileColors.put(TileType.EMPTY_CLB, QColor.fromRgb(240, 141, 45));
		tileColors.put(TileType.EMPTY_CLB_BUFFER, QColor.fromRgb(240, 141, 45));
		tileColors.put(TileType.EMPTY_CLKC, QColor.fromRgb(240, 141, 45));
		tileColors.put(TileType.EMPTY_CLKC_LL, QColor.fromRgb(240, 141, 45));
		tileColors.put(TileType.EMPTY_CLKC_LLTB, QColor.fromRgb(240, 141, 45));
		tileColors.put(TileType.EMPTY_CLKH_LL, QColor.fromRgb(240, 141, 45));
		tileColors.put(TileType.EMPTY_CLKL_IOIS_LL, QColor.fromRgb(240, 141, 45));
		tileColors.put(TileType.EMPTY_CLKL_LL, QColor.fromRgb(240, 141, 45));
		tileColors.put(TileType.EMPTY_CLKR_IOIS_LL, QColor.fromRgb(240, 141, 45));
		tileColors.put(TileType.EMPTY_CLKR_LL, QColor.fromRgb(240, 141, 45));
		tileColors.put(TileType.EMPTY_CLKV_DCM, QColor.fromRgb(240, 141, 45));
		tileColors.put(TileType.EMPTY_CLK_BUFGCTRL, QColor.fromRgb(240, 141, 45));
		tileColors.put(TileType.EMPTY_CLK_IOB, QColor.fromRgb(240, 141, 45));
		tileColors.put(TileType.EMPTY_CNR, QColor.fromRgb(240, 141, 45));
		tileColors.put(TileType.EMPTY_CORNER, QColor.fromRgb(240, 141, 45));
		tileColors.put(TileType.EMPTY_DCM, QColor.fromRgb(240, 141, 45));
		tileColors.put(TileType.EMPTY_DCM_TERM, QColor.fromRgb(240, 141, 45));
		tileColors.put(TileType.EMPTY_DSP, black);
		tileColors.put(TileType.EMPTY_EDGE_BRAM, QColor.fromRgb(240, 141, 45));
		tileColors.put(TileType.EMPTY_EDGE_CONFIG, QColor.fromRgb(240, 141, 45));
		tileColors.put(TileType.EMPTY_EDGE_DSP, QColor.fromRgb(240, 141, 45));
		tileColors.put(TileType.EMPTY_EDGE_MGT, QColor.fromRgb(240, 141, 45));
		tileColors.put(TileType.EMPTY_GCLKH, QColor.fromRgb(240, 141, 45));
		tileColors.put(TileType.EMPTY_GCLKVML_LL, QColor.fromRgb(240, 141, 45));
		tileColors.put(TileType.EMPTY_GCLKVMR_LL, QColor.fromRgb(240, 141, 45));
		tileColors.put(TileType.EMPTY_HCLK, QColor.fromRgb(240, 141, 45));
		tileColors.put(TileType.EMPTY_HCLK_MGT, QColor.fromRgb(240, 141, 45));
		tileColors.put(TileType.EMPTY_IOIS, QColor.fromRgb(240, 141, 45));
		tileColors.put(TileType.EMPTY_MACC, QColor.fromRgb(240, 141, 45));
		tileColors.put(TileType.EMPTY_MGT, QColor.fromRgb(240, 141, 45));
		tileColors.put(TileType.EMPTY_MONITOR, QColor.fromRgb(240, 141, 45));
		tileColors.put(TileType.EMPTY_PPC, QColor.fromRgb(240, 141, 45));
		tileColors.put(TileType.EMPTY_TIOI, QColor.fromRgb(240, 141, 45));
		tileColors.put(TileType.EMPTY_TTERM, QColor.fromRgb(240, 141, 45));
		tileColors.put(TileType.EMPTY_VBRK, QColor.fromRgb(240, 141, 45));
		tileColors.put(TileType.EMP_LIOB, darkGreen);
		tileColors.put(TileType.EMP_RIOB, darkGreen);
		tileColors.put(TileType.GBRKB, darkBlue);
		tileColors.put(TileType.GBRKC, darkBlue);
		tileColors.put(TileType.GBRKT, darkBlue);
		tileColors.put(TileType.GBRKV, darkBlue);
		tileColors.put(TileType.GCLKB, darkBlue);
		tileColors.put(TileType.GCLKC, darkBlue);
		tileColors.put(TileType.GCLKH, darkBlue);
		tileColors.put(TileType.GCLKHL_50A, darkBlue);
		tileColors.put(TileType.GCLKHR_50A, darkBlue);
		tileColors.put(TileType.GCLKH_PCI_CE_N, darkBlue);
		tileColors.put(TileType.GCLKH_PCI_CE_S, darkBlue);
		tileColors.put(TileType.GCLKH_PCI_CE_S_50A, darkBlue);
		tileColors.put(TileType.GCLKT, darkBlue);
		tileColors.put(TileType.GCLKV, darkBlue);
		tileColors.put(TileType.GCLKVC, darkBlue);
		tileColors.put(TileType.GCLKVM, darkBlue);
		tileColors.put(TileType.GCLKVML, darkBlue);
		tileColors.put(TileType.GCLKVMR, darkBlue);
		tileColors.put(TileType.GCLKV_IOIS, darkBlue);
		tileColors.put(TileType.GCLKV_IOISL, darkBlue);
		tileColors.put(TileType.GCLKV_IOISR, darkBlue);
		tileColors.put(TileType.GIGABIT10_IOI, black);
		tileColors.put(TileType.GIGABIT_IOI, black);
		tileColors.put(TileType.GT3, black);
		tileColors.put(TileType.GTH_BOT, black);
		tileColors.put(TileType.GTH_L_BOT, black);
		tileColors.put(TileType.GTH_L_TOP, black);
		tileColors.put(TileType.GTH_TOP, black);
		tileColors.put(TileType.GTPDUAL_BOT, black);
		tileColors.put(TileType.GTPDUAL_BOT_UNUSED, black);
		tileColors.put(TileType.GTPDUAL_CLB_FEEDTHRU, black);
		tileColors.put(TileType.GTPDUAL_DSP_FEEDTHRU, black);
		tileColors.put(TileType.GTPDUAL_INT_FEEDTHRU, black);
		tileColors.put(TileType.GTPDUAL_LEFT_CLB_FEEDTHRU, black);
		tileColors.put(TileType.GTPDUAL_LEFT_DSP_FEEDTHRU, black);
		tileColors.put(TileType.GTPDUAL_LEFT_INT_FEEDTHRU, black);
		tileColors.put(TileType.GTPDUAL_TOP, black);
		tileColors.put(TileType.GTPDUAL_TOP_UNUSED, black);
		tileColors.put(TileType.GTP_INT_INTERFACE, black);
		tileColors.put(TileType.GTX, black);
		tileColors.put(TileType.GTX_DUMMY, black);
		tileColors.put(TileType.GTX_INT_INTERFACE, black);
		tileColors.put(TileType.GTX_LEFT, black);
		tileColors.put(TileType.GTX_LEFT_INT_INTERFACE, black);
		tileColors.put(TileType.GTX_L_TERM_INT, black);
		tileColors.put(TileType.GT_INT_INTERFACE_TERM, black);
		tileColors.put(TileType.GT_L_INT_INTERFACE, black);
		tileColors.put(TileType.HCLK, cyan);
		tileColors.put(TileType.HCLK_BRAM, cyan);
		tileColors.put(TileType.HCLK_BRAM_FEEDTHRU, cyan);
		tileColors.put(TileType.HCLK_BRAM_FEEDTHRU_FOLD, cyan);
		tileColors.put(TileType.HCLK_BRAM_FX, cyan);
		tileColors.put(TileType.HCLK_BRAM_MGT, cyan);
		tileColors.put(TileType.HCLK_BRAM_MGT_LEFT, cyan);
		tileColors.put(TileType.HCLK_CENTER, cyan);
		tileColors.put(TileType.HCLK_CENTER_ABOVE_CFG, cyan);
		tileColors.put(TileType.HCLK_CLB, cyan);
		tileColors.put(TileType.HCLK_CLBLL, cyan);
		tileColors.put(TileType.HCLK_CLBLM, cyan);
		tileColors.put(TileType.HCLK_CLBLM_MGT, cyan);
		tileColors.put(TileType.HCLK_CLBLM_MGT_LEFT, cyan);
		tileColors.put(TileType.HCLK_CLB_XL_CLE, cyan);
		tileColors.put(TileType.HCLK_CLB_XL_CLE_FOLD, cyan);
		tileColors.put(TileType.HCLK_CLB_XL_INT, cyan);
		tileColors.put(TileType.HCLK_CLB_XL_INT_FOLD, cyan);
		tileColors.put(TileType.HCLK_CLB_XM_CLE, cyan);
		tileColors.put(TileType.HCLK_CLB_XM_CLE_FOLD, cyan);
		tileColors.put(TileType.HCLK_CLB_XM_INT, cyan);
		tileColors.put(TileType.HCLK_CLB_XM_INT_FOLD, cyan);
		tileColors.put(TileType.HCLK_CMT_BOT, cyan);
		tileColors.put(TileType.HCLK_CMT_CMT, cyan);
		tileColors.put(TileType.HCLK_CMT_CMT_MGT, cyan);
		tileColors.put(TileType.HCLK_CMT_IOI, cyan);
		tileColors.put(TileType.HCLK_CMT_TOP, cyan);
		tileColors.put(TileType.HCLK_DCM, cyan);
		tileColors.put(TileType.HCLK_DCMIOB, cyan);
		tileColors.put(TileType.HCLK_DSP, cyan);
		tileColors.put(TileType.HCLK_FT, cyan);
		tileColors.put(TileType.HCLK_GT3, cyan);
		tileColors.put(TileType.HCLK_GTH, cyan);
		tileColors.put(TileType.HCLK_GTH_LEFT, cyan);
		tileColors.put(TileType.HCLK_GTX, cyan);
		tileColors.put(TileType.HCLK_GTX_DUMMY, cyan);
		tileColors.put(TileType.HCLK_GTX_LEFT, cyan);
		tileColors.put(TileType.HCLK_GT_EMP, cyan);
		tileColors.put(TileType.HCLK_INNER_IOI, cyan);
		tileColors.put(TileType.HCLK_INT_INTERFACE, cyan);
		tileColors.put(TileType.HCLK_IOB, cyan);
		tileColors.put(TileType.HCLK_IOBDCM, cyan);
		tileColors.put(TileType.HCLK_IOB_CMT_BOT, cyan);
		tileColors.put(TileType.HCLK_IOB_CMT_BOT_MGT, cyan);
		tileColors.put(TileType.HCLK_IOB_CMT_MID, cyan);
		tileColors.put(TileType.HCLK_IOB_CMT_MID_MGT, cyan);
		tileColors.put(TileType.HCLK_IOB_CMT_TOP, cyan);
		tileColors.put(TileType.HCLK_IOB_CMT_TOP_MGT, cyan);
		tileColors.put(TileType.HCLK_IOI, cyan);
		tileColors.put(TileType.HCLK_IOIL_BOT_DN, cyan);
		tileColors.put(TileType.HCLK_IOIL_BOT_SPLIT, cyan);
		tileColors.put(TileType.HCLK_IOIL_BOT_UP, cyan);
		tileColors.put(TileType.HCLK_IOIL_EMP, cyan);
		tileColors.put(TileType.HCLK_IOIL_INT, cyan);
		tileColors.put(TileType.HCLK_IOIL_INT_FOLD, cyan);
		tileColors.put(TileType.HCLK_IOIL_TOP_DN, cyan);
		tileColors.put(TileType.HCLK_IOIL_TOP_SPLIT, cyan);
		tileColors.put(TileType.HCLK_IOIL_TOP_UP, cyan);
		tileColors.put(TileType.HCLK_IOIR_BOT_DN, cyan);
		tileColors.put(TileType.HCLK_IOIR_BOT_SPLIT, cyan);
		tileColors.put(TileType.HCLK_IOIR_BOT_UP, cyan);
		tileColors.put(TileType.HCLK_IOIR_EMP, cyan);
		tileColors.put(TileType.HCLK_IOIR_INT, cyan);
		tileColors.put(TileType.HCLK_IOIR_INT_FOLD, cyan);
		tileColors.put(TileType.HCLK_IOIR_TOP_DN, cyan);
		tileColors.put(TileType.HCLK_IOIR_TOP_SPLIT, cyan);
		tileColors.put(TileType.HCLK_IOIR_TOP_UP, cyan);
		tileColors.put(TileType.HCLK_IOIS_DCI, cyan);
		tileColors.put(TileType.HCLK_IOIS_LVDS, cyan);
		tileColors.put(TileType.HCLK_IOI_BOTCEN, cyan);
		tileColors.put(TileType.HCLK_IOI_BOTCEN_MGT, cyan);
		tileColors.put(TileType.HCLK_IOI_CENTER, cyan);
		tileColors.put(TileType.HCLK_IOI_CMT, cyan);
		tileColors.put(TileType.HCLK_IOI_CMT_MGT, cyan);
		tileColors.put(TileType.HCLK_IOI_LTERM, cyan);
		tileColors.put(TileType.HCLK_IOI_LTERM_BOT25, cyan);
		tileColors.put(TileType.HCLK_IOI_RTERM, cyan);
		tileColors.put(TileType.HCLK_IOI_RTERM_BOT25, cyan);
		tileColors.put(TileType.HCLK_IOI_TOPCEN, cyan);
		tileColors.put(TileType.HCLK_IOI_TOPCEN_MGT, cyan);
		tileColors.put(TileType.HCLK_LIOB, cyan);
		tileColors.put(TileType.HCLK_MGT, cyan);
		tileColors.put(TileType.HCLK_OUTER_IOI, cyan);
		tileColors.put(TileType.HCLK_PCIE_BRAM, cyan);
		tileColors.put(TileType.HCLK_PPC, cyan);
		tileColors.put(TileType.HCLK_PPC_TERM, cyan);
		tileColors.put(TileType.HCLK_QBUF_L, cyan);
		tileColors.put(TileType.HCLK_QBUF_R, cyan);
		tileColors.put(TileType.HCLK_TERM, cyan);
		tileColors.put(TileType.HCLK_TERM_L, cyan);
		tileColors.put(TileType.HCLK_TERM_R, cyan);
		tileColors.put(TileType.HCLK_VBRK, cyan);
		tileColors.put(TileType.HCLK_VBRK_R, cyan);
		tileColors.put(TileType.HCLK_VFRAME, cyan);
		tileColors.put(TileType.INT, darkYellow);
		tileColors.put(TileType.INT_BRAM, darkYellow);
		tileColors.put(TileType.INT_BRAM_BRK, darkYellow);
		tileColors.put(TileType.INT_BRK, darkYellow);
		tileColors.put(TileType.INT_BUFS_L, darkYellow);
		tileColors.put(TileType.INT_BUFS_R, darkYellow);
		tileColors.put(TileType.INT_BUFS_R_MON, darkYellow);
		tileColors.put(TileType.INT_GCLK, darkYellow);
		tileColors.put(TileType.INT_HCLK_BUFS, cyan);
		tileColors.put(TileType.INT_INTERFACE, darkYellow);
		tileColors.put(TileType.INT_INTERFACE_CARRY, darkYellow);
		tileColors.put(TileType.INT_INTERFACE_IOI, darkYellow);
		tileColors.put(TileType.INT_INTERFACE_IOI_DCMBOT, darkYellow);
		tileColors.put(TileType.INT_INTERFACE_LTERM, darkYellow);
		tileColors.put(TileType.INT_INTERFACE_REGC, darkYellow);
		tileColors.put(TileType.INT_INTERFACE_RTERM, darkYellow);
		tileColors.put(TileType.INT_INTERFACE_TERM, darkYellow);
		tileColors.put(TileType.INT_LTERM, darkYellow);
		tileColors.put(TileType.INT_RTERM, darkYellow);
		tileColors.put(TileType.INT_SO, darkYellow);
		tileColors.put(TileType.INT_SO_DCM0, darkYellow);
		tileColors.put(TileType.INT_TERM, darkYellow);
		tileColors.put(TileType.INT_TERM_BRK, darkYellow);
		tileColors.put(TileType.IOI, darkGreen);
		tileColors.put(TileType.IOIS_LC, darkGreen);
		tileColors.put(TileType.IOIS_LC_L, darkGreen);
		tileColors.put(TileType.IOIS_NC, darkGreen);
		tileColors.put(TileType.IOIS_NC_L, darkGreen);
		tileColors.put(TileType.IOI_BTERM, darkGreen);
		tileColors.put(TileType.IOI_BTERM_BUFPLL, darkGreen);
		tileColors.put(TileType.IOI_BTERM_CLB, darkGreen);
		tileColors.put(TileType.IOI_BTERM_REGB, darkGreen);
		tileColors.put(TileType.IOI_INT, darkYellow);
		tileColors.put(TileType.IOI_LTERM, darkGreen);
		tileColors.put(TileType.IOI_LTERM_LOWER_BOT, darkGreen);
		tileColors.put(TileType.IOI_LTERM_LOWER_TOP, darkGreen);
		tileColors.put(TileType.IOI_LTERM_UPPER_BOT, darkGreen);
		tileColors.put(TileType.IOI_LTERM_UPPER_TOP, darkGreen);
		tileColors.put(TileType.IOI_L_INT_INTERFACE, darkGreen);
		tileColors.put(TileType.IOI_L_INT_INTERFACE_TERM, darkGreen);
		tileColors.put(TileType.IOI_PCI_CE_LEFT, darkGreen);
		tileColors.put(TileType.IOI_PCI_CE_RIGHT, darkGreen);
		tileColors.put(TileType.IOI_RTERM, darkGreen);
		tileColors.put(TileType.IOI_RTERM_LOWER_BOT, darkGreen);
		tileColors.put(TileType.IOI_RTERM_LOWER_TOP, darkGreen);
		tileColors.put(TileType.IOI_RTERM_UPPER_BOT, darkGreen);
		tileColors.put(TileType.IOI_RTERM_UPPER_TOP, darkGreen);
		tileColors.put(TileType.IOI_TTERM, darkGreen);
		tileColors.put(TileType.IOI_TTERM_BUFPLL, darkGreen);
		tileColors.put(TileType.IOI_TTERM_CLB, darkGreen);
		tileColors.put(TileType.IOI_TTERM_REGT, darkGreen);
		tileColors.put(TileType.LBPPC, black);
		tileColors.put(TileType.LBRAM, darkMagenta);
		tileColors.put(TileType.LBRAMS2E_BOTP, darkMagenta);
		tileColors.put(TileType.LBRAMS2E_TOPP, darkMagenta);
		tileColors.put(TileType.LBRAM_BOTP, darkMagenta);
		tileColors.put(TileType.LBRAM_BOTS, darkMagenta);
		tileColors.put(TileType.LBRAM_BOTS_GCLK, darkMagenta);
		tileColors.put(TileType.LBRAM_TOPP, darkMagenta);
		tileColors.put(TileType.LBRAM_TOPS, darkMagenta);
		tileColors.put(TileType.LBRAM_TOPS_GCLK, darkMagenta);
		tileColors.put(TileType.LEFT, darkGreen);
		tileColors.put(TileType.LEFT_PCI_BOT, darkBlue);
		tileColors.put(TileType.LEFT_PCI_TOP, darkBlue);
		tileColors.put(TileType.LEMPTY0X2, black);
		tileColors.put(TileType.LEMPTY16X4, black);
		tileColors.put(TileType.LIBUFS, darkGreen);
		tileColors.put(TileType.LIBUFS_CLK_PCI, darkGreen);
		tileColors.put(TileType.LIBUFS_PCI, darkGreen);
		tileColors.put(TileType.LIOB, darkGreen);
		tileColors.put(TileType.LIOB_FT, darkGreen);
		tileColors.put(TileType.LIOB_MON, darkGreen);
		tileColors.put(TileType.LIOB_PCI, darkGreen);
		tileColors.put(TileType.LIOB_RDY, darkGreen);
		tileColors.put(TileType.LIOI, darkGreen);
		tileColors.put(TileType.LIOIS, darkGreen);
		tileColors.put(TileType.LIOIS_BRK, darkGreen);
		tileColors.put(TileType.LIOIS_CLK_PCI, darkGreen);
		tileColors.put(TileType.LIOIS_CLK_PCI_BRK, darkGreen);
		tileColors.put(TileType.LIOIS_PCI, darkGreen);
		tileColors.put(TileType.LIOI_BRK, darkGreen);
		tileColors.put(TileType.LIOI_INT, darkYellow);
		tileColors.put(TileType.LIOI_INT_BRK, darkYellow);
		tileColors.put(TileType.LL, black);
		tileColors.put(TileType.LLPPC_X0Y0_INT, black);
		tileColors.put(TileType.LLPPC_X1Y0_INT, black);
		tileColors.put(TileType.LPPC_X0Y0_INT, black);
		tileColors.put(TileType.LPPC_X1Y0_INT, black);
		tileColors.put(TileType.LR, black);
		tileColors.put(TileType.LR_BRKH, black);
		tileColors.put(TileType.LR_CLKH, black);
		tileColors.put(TileType.LR_GCLKH, black);
		tileColors.put(TileType.LR_IOIS, darkGreen);
		tileColors.put(TileType.LR_LOWER, black);
		tileColors.put(TileType.LR_UPPER, black);
		tileColors.put(TileType.LTERM, darkGray);
		tileColors.put(TileType.LTERM010, darkGray);
		tileColors.put(TileType.LTERM1, darkGray);
		tileColors.put(TileType.LTERM2, darkGray);
		tileColors.put(TileType.LTERM210, darkGray);
		tileColors.put(TileType.LTERM210_PCI, darkGray);
		tileColors.put(TileType.LTERM3, darkGray);
		tileColors.put(TileType.LTERM321, darkGray);
		tileColors.put(TileType.LTERM323, darkGray);
		tileColors.put(TileType.LTERM323_PCI, darkGray);
		tileColors.put(TileType.LTERM4, darkGray);
		tileColors.put(TileType.LTERM4B, darkGray);
		tileColors.put(TileType.LTERM4CLK, darkGray);
		tileColors.put(TileType.LTERMCLK, darkGray);
		tileColors.put(TileType.LTERMCLKA, darkGray);
		tileColors.put(TileType.L_TERM_INT, darkGray);
		tileColors.put(TileType.L_TERM_PPC, darkGray);
		tileColors.put(TileType.L_TERM_PPC_EXT, darkGray);
		tileColors.put(TileType.MACC0_SMALL, darkCyan);
		tileColors.put(TileType.MACC0_SMALL_BOT, darkCyan);
		tileColors.put(TileType.MACC1_SMALL, darkCyan);
		tileColors.put(TileType.MACC2_FEEDTHRUH, darkCyan);
		tileColors.put(TileType.MACC2_GCLKH_FEEDTHRUA, darkCyan);
		tileColors.put(TileType.MACC2_SMALL, darkCyan);
		tileColors.put(TileType.MACC3_SMALL, darkCyan);
		tileColors.put(TileType.MACC3_SMALL_BRK, darkCyan);
		tileColors.put(TileType.MACC3_SMALL_TOP, darkCyan);
		tileColors.put(TileType.MACCSITE2, darkCyan);
		tileColors.put(TileType.MACCSITE2_BOT, darkCyan);
		tileColors.put(TileType.MACCSITE2_BRK, darkCyan);
		tileColors.put(TileType.MACCSITE2_DUMMY, darkCyan);
		tileColors.put(TileType.MACCSITE2_TOP, darkCyan);
		tileColors.put(TileType.MBRAM, darkMagenta);
		tileColors.put(TileType.MBRAMS2E, darkMagenta);
		tileColors.put(TileType.MCB_CAP_CLKPN, black);
		tileColors.put(TileType.MCB_CAP_INT, black);
		tileColors.put(TileType.MCB_CAP_INT_BRK, black);
		tileColors.put(TileType.MCB_CNR_TOP, black);
		tileColors.put(TileType.MCB_DUMMY, black);
		tileColors.put(TileType.MCB_HCLK, cyan);
		tileColors.put(TileType.MCB_INT, black);
		tileColors.put(TileType.MCB_INT_BOT, black);
		tileColors.put(TileType.MCB_INT_BOT25, black);
		tileColors.put(TileType.MCB_INT_DQI, black);
		tileColors.put(TileType.MCB_INT_DUMMY, black);
		tileColors.put(TileType.MCB_INT_ULDM, black);
		tileColors.put(TileType.MCB_L, black);
		tileColors.put(TileType.MCB_L_BOT, black);
		tileColors.put(TileType.MCB_MUI0R, black);
		tileColors.put(TileType.MCB_MUI0W, black);
		tileColors.put(TileType.MCB_MUI1R, black);
		tileColors.put(TileType.MCB_MUI1W, black);
		tileColors.put(TileType.MCB_MUI2, black);
		tileColors.put(TileType.MCB_MUI3, black);
		tileColors.put(TileType.MCB_MUI4, black);
		tileColors.put(TileType.MCB_MUI5, black);
		tileColors.put(TileType.MCB_MUI_DUMMY, black);
		tileColors.put(TileType.MCB_REGH, black);
		tileColors.put(TileType.MGT_AL, black);
		tileColors.put(TileType.MGT_AL_BOT, black);
		tileColors.put(TileType.MGT_AL_MID, black);
		tileColors.put(TileType.MGT_AR, black);
		tileColors.put(TileType.MGT_AR_BOT, black);
		tileColors.put(TileType.MGT_AR_MID, black);
		tileColors.put(TileType.MGT_BL, black);
		tileColors.put(TileType.MGT_BR, black);
		tileColors.put(TileType.MGT_R, black);
		tileColors.put(TileType.MK_B_IOIS, black);
		tileColors.put(TileType.MK_CLKB, black);
		tileColors.put(TileType.MK_CLKT, black);
		tileColors.put(TileType.MK_T_IOIS, black);
		tileColors.put(TileType.ML_BCLKTERM012, black);
		tileColors.put(TileType.ML_BCLKTERM123, black);
		tileColors.put(TileType.ML_BRAMSITE_IOIS, black);
		tileColors.put(TileType.ML_BRAM_IOIS, black);
		tileColors.put(TileType.ML_CLKB, black);
		tileColors.put(TileType.ML_CLKH, black);
		tileColors.put(TileType.ML_CLKT, black);
		tileColors.put(TileType.ML_CNR_BTERM, black);
		tileColors.put(TileType.ML_LR_CLKH, black);
		tileColors.put(TileType.ML_TBS_IOIS, black);
		tileColors.put(TileType.ML_TB_IOIS, black);
		tileColors.put(TileType.ML_TCLKTERM210, black);
		tileColors.put(TileType.ML_TTERM010, black);
		tileColors.put(TileType.NULL, black);
		tileColors.put(TileType.PB, black);
		tileColors.put(TileType.PCIE, black);
		tileColors.put(TileType.PCIE_B, black);
		tileColors.put(TileType.PCIE_BRAM, black);
		tileColors.put(TileType.PCIE_BRKH, black);
		tileColors.put(TileType.PCIE_INT_INTERFACE, black);
		tileColors.put(TileType.PCIE_INT_INTERFACE_L, black);
		tileColors.put(TileType.PCIE_INT_INTERFACE_R, black);
		tileColors.put(TileType.PCIE_T, black);
		tileColors.put(TileType.PCIE_TOP, black);
		tileColors.put(TileType.PCIE_TOP_CLB_FEEDTHRU, black);
		tileColors.put(TileType.PCIE_TOP_INT_FEEDTHRU, black);
		tileColors.put(TileType.PCIE_TOP_UNUSED, black);
		tileColors.put(TileType.PPC_B, black);
		tileColors.put(TileType.PPC_BR, black);
		tileColors.put(TileType.PPC_BRAM_B, black);
		tileColors.put(TileType.PPC_BRAM_T, black);
		tileColors.put(TileType.PPC_B_PB, black);
		tileColors.put(TileType.PPC_B_TERM, black);
		tileColors.put(TileType.PPC_L_INT_INTERFACE, black);
		tileColors.put(TileType.PPC_R, black);
		tileColors.put(TileType.PPC_R_INT_INTERFACE, black);
		tileColors.put(TileType.PPC_R_PB, black);
		tileColors.put(TileType.PPC_R_PT, black);
		tileColors.put(TileType.PPC_T, black);
		tileColors.put(TileType.PPC_TR, black);
		tileColors.put(TileType.PPC_T_PT, black);
		tileColors.put(TileType.PPC_T_TERM, black);
		tileColors.put(TileType.PT, black);
		tileColors.put(TileType.PTERMB, black);
		tileColors.put(TileType.PTERMBR, black);
		tileColors.put(TileType.PTERMR, black);
		tileColors.put(TileType.PTERMT, black);
		tileColors.put(TileType.PTERMTR, black);
		tileColors.put(TileType.RAMB_BOT, black);
		tileColors.put(TileType.RAMB_BOT_BTERM, black);
		tileColors.put(TileType.RAMB_TOP, black);
		tileColors.put(TileType.RAMB_TOP_TTERM, black);
		tileColors.put(TileType.RBPPC, black);
		tileColors.put(TileType.RBRAM, darkMagenta);
		tileColors.put(TileType.RBRAMS2E_BOTP, darkMagenta);
		tileColors.put(TileType.RBRAMS2E_TOPP, darkMagenta);
		tileColors.put(TileType.RBRAM_BOTP, darkMagenta);
		tileColors.put(TileType.RBRAM_BOTS, darkMagenta);
		tileColors.put(TileType.RBRAM_BOTS_GCLK, darkMagenta);
		tileColors.put(TileType.RBRAM_TOPP, darkMagenta);
		tileColors.put(TileType.RBRAM_TOPS, darkMagenta);
		tileColors.put(TileType.RBRAM_TOPS_GCLK, darkMagenta);
		tileColors.put(TileType.REGC_CLE, darkBlue);
		tileColors.put(TileType.REGC_INT, darkBlue);
		tileColors.put(TileType.REGH_BRAM_FEEDTHRU, darkBlue);
		tileColors.put(TileType.REGH_BRAM_FEEDTHRU_L_GCLK, darkBlue);
		tileColors.put(TileType.REGH_BRAM_FEEDTHRU_R_GCLK, darkBlue);
		tileColors.put(TileType.REGH_CLEXL_CLE, darkBlue);
		tileColors.put(TileType.REGH_CLEXL_INT, darkBlue);
		tileColors.put(TileType.REGH_CLEXL_INT_CLK, darkBlue);
		tileColors.put(TileType.REGH_CLEXM_CLE, darkBlue);
		tileColors.put(TileType.REGH_CLEXM_INT, darkBlue);
		tileColors.put(TileType.REGH_CLEXM_INT_GCLKL, darkBlue);
		tileColors.put(TileType.REGH_DSP_CLB, darkBlue);
		tileColors.put(TileType.REGH_DSP_INT, darkBlue);
		tileColors.put(TileType.REGH_DSP_L, darkBlue);
		tileColors.put(TileType.REGH_DSP_L_NOCLK, darkBlue);
		tileColors.put(TileType.REGH_DSP_R, darkBlue);
		tileColors.put(TileType.REGH_IOI, darkBlue);
		tileColors.put(TileType.REGH_IOI_BOT25, darkBlue);
		tileColors.put(TileType.REGH_IOI_LTERM, darkBlue);
		tileColors.put(TileType.REGH_IOI_RTERM, darkBlue);
		tileColors.put(TileType.REGH_LIOI_INT, darkBlue);
		tileColors.put(TileType.REGH_LIOI_INT_BOT25, darkBlue);
		tileColors.put(TileType.REGH_RIOI, darkBlue);
		tileColors.put(TileType.REGH_RIOI_BOT25, darkBlue);
		tileColors.put(TileType.REGH_RIOI_INT, darkBlue);
		tileColors.put(TileType.REGH_RIOI_INT_BOT25, darkBlue);
		tileColors.put(TileType.REG_B, darkBlue);
		tileColors.put(TileType.REG_B_BTERM, darkBlue);
		tileColors.put(TileType.REG_C_CMT, darkBlue);
		tileColors.put(TileType.REG_L, darkBlue);
		tileColors.put(TileType.REG_LB, darkBlue);
		tileColors.put(TileType.REG_R, darkBlue);
		tileColors.put(TileType.REG_RB, darkBlue);
		tileColors.put(TileType.REG_T, darkBlue);
		tileColors.put(TileType.REG_T_TTERM, darkBlue);
		tileColors.put(TileType.REG_V, darkBlue);
		tileColors.put(TileType.REG_V_BRK, darkBlue);
		tileColors.put(TileType.REG_V_BTERM, darkBlue);
		tileColors.put(TileType.REG_V_HCLK, darkBlue);
		tileColors.put(TileType.REG_V_HCLKBUF_BOT, darkBlue);
		tileColors.put(TileType.REG_V_HCLKBUF_TOP, darkBlue);
		tileColors.put(TileType.REG_V_HCLK_BOT25, darkBlue);
		tileColors.put(TileType.REG_V_MEMB_BOT, darkBlue);
		tileColors.put(TileType.REG_V_MEMB_TOP, darkBlue);
		tileColors.put(TileType.REG_V_MIDBUF_BOT, darkBlue);
		tileColors.put(TileType.REG_V_MIDBUF_TOP, darkBlue);
		tileColors.put(TileType.REG_V_TTERM, darkBlue);
		tileColors.put(TileType.REMPTY0X2, black);
		tileColors.put(TileType.REMPTY16X4, black);
		tileColors.put(TileType.RIBUFS, darkGreen);
		tileColors.put(TileType.RIBUFS_BRK, darkGreen);
		tileColors.put(TileType.RIBUFS_CLK_PCI, darkGreen);
		tileColors.put(TileType.RIBUFS_CLK_PCI_BRK, darkGreen);
		tileColors.put(TileType.RIBUFS_PCI, darkGreen);
		tileColors.put(TileType.RIGHT, darkGreen);
		tileColors.put(TileType.RIGHT_PCI_BOT, darkBlue);
		tileColors.put(TileType.RIGHT_PCI_TOP, darkBlue);
		tileColors.put(TileType.RIOB, darkGreen);
		tileColors.put(TileType.RIOB_PCI, darkGreen);
		tileColors.put(TileType.RIOB_RDY, darkGreen);
		tileColors.put(TileType.RIOI, darkGreen);
		tileColors.put(TileType.RIOIS, darkGreen);
		tileColors.put(TileType.RIOIS_CLK_PCI, darkGreen);
		tileColors.put(TileType.RIOIS_PCI, darkGreen);
		tileColors.put(TileType.RIOI_BRK, darkGreen);
		tileColors.put(TileType.RPPC_X0Y0_INT, black);
		tileColors.put(TileType.RPPC_X1Y0_INT, black);
		tileColors.put(TileType.RTERM, darkGray);
		tileColors.put(TileType.RTERM010, darkGray);
		tileColors.put(TileType.RTERM1, darkGray);
		tileColors.put(TileType.RTERM2, darkGray);
		tileColors.put(TileType.RTERM210, darkGray);
		tileColors.put(TileType.RTERM210_PCI, darkGray);
		tileColors.put(TileType.RTERM3, darkGray);
		tileColors.put(TileType.RTERM321, darkGray);
		tileColors.put(TileType.RTERM323, darkGray);
		tileColors.put(TileType.RTERM323_PCI, darkGray);
		tileColors.put(TileType.RTERM4, darkGray);
		tileColors.put(TileType.RTERM4B, darkGray);
		tileColors.put(TileType.RTERM4CLK, darkGray);
		tileColors.put(TileType.RTERM4CLKB, darkGray);
		tileColors.put(TileType.RTERMCLKA, darkGray);
		tileColors.put(TileType.RTERMCLKB, darkGray);
		tileColors.put(TileType.R_TERM_INT, darkGray);
		tileColors.put(TileType.R_TERM_INT_D, darkGray);
		tileColors.put(TileType.R_TERM_PPC, darkGray);
		tileColors.put(TileType.SITE_FEEDTHRU, black);
		tileColors.put(TileType.SYS_MON, black);
		tileColors.put(TileType.TBSTERM, darkGray);
		tileColors.put(TileType.TB_IOIS, darkGreen);
		tileColors.put(TileType.TCLKTERM2, darkGray);
		tileColors.put(TileType.TCLKTERM210, darkGray);
		tileColors.put(TileType.TCLKTERM3, darkGray);
		tileColors.put(TileType.TCLKTERM321, darkGray);
		tileColors.put(TileType.TGCLKVTERM, darkGray);
		tileColors.put(TileType.TGIGABIT, black);
		tileColors.put(TileType.TGIGABIT10, black);
		tileColors.put(TileType.TGIGABIT10_INT0, black);
		tileColors.put(TileType.TGIGABIT10_INT1, black);
		tileColors.put(TileType.TGIGABIT10_INT2, black);
		tileColors.put(TileType.TGIGABIT10_INT3, black);
		tileColors.put(TileType.TGIGABIT10_INT4, black);
		tileColors.put(TileType.TGIGABIT10_INT5, black);
		tileColors.put(TileType.TGIGABIT10_INT6, black);
		tileColors.put(TileType.TGIGABIT10_INT7, black);
		tileColors.put(TileType.TGIGABIT10_INT8, black);
		tileColors.put(TileType.TGIGABIT10_INT_TERM, black);
		tileColors.put(TileType.TGIGABIT10_IOI_TERM, black);
		tileColors.put(TileType.TGIGABIT10_TERM, black);
		tileColors.put(TileType.TGIGABIT_INT0, black);
		tileColors.put(TileType.TGIGABIT_INT1, black);
		tileColors.put(TileType.TGIGABIT_INT2, black);
		tileColors.put(TileType.TGIGABIT_INT3, black);
		tileColors.put(TileType.TGIGABIT_INT4, black);
		tileColors.put(TileType.TGIGABIT_INT_TERM, black);
		tileColors.put(TileType.TGIGABIT_IOI_TERM, black);
		tileColors.put(TileType.TGIGABIT_TERM, black);
		tileColors.put(TileType.TIBUFS, darkGreen);
		tileColors.put(TileType.TIOB, darkGreen);
		tileColors.put(TileType.TIOB_SINGLE, darkGreen);
		tileColors.put(TileType.TIOIB, darkGreen);
		tileColors.put(TileType.TIOIS, darkGreen);
		tileColors.put(TileType.TIOI_INNER, darkGreen);
		tileColors.put(TileType.TIOI_INNER_UNUSED, darkGreen);
		tileColors.put(TileType.TIOI_OUTER, darkGreen);
		tileColors.put(TileType.TL_DLLIOB, darkGreen);
		tileColors.put(TileType.TOP, darkGreen);
		tileColors.put(TileType.TPPC_X0Y0_INT, black);
		tileColors.put(TileType.TPPC_X1Y0_INT, black);
		tileColors.put(TileType.TR_DLLIOB, darkGreen);
		tileColors.put(TileType.TTERM, darkGray);
		tileColors.put(TileType.TTERM010, darkGray);
		tileColors.put(TileType.TTERM1, darkGray);
		tileColors.put(TileType.TTERM1_MACC, darkGray);
		tileColors.put(TileType.TTERM2, darkGray);
		tileColors.put(TileType.TTERM210, darkGray);
		tileColors.put(TileType.TTERM2CLK, darkGray);
		tileColors.put(TileType.TTERM3, darkGray);
		tileColors.put(TileType.TTERM321, darkGray);
		tileColors.put(TileType.TTERM323, darkGray);
		tileColors.put(TileType.TTERM4, darkGray);
		tileColors.put(TileType.TTERM4CLK, darkGray);
		tileColors.put(TileType.TTERM4_BRAM2, darkGray);
		tileColors.put(TileType.TTERMCLK, darkGray);
		tileColors.put(TileType.TTERMCLKA, darkGray);
		tileColors.put(TileType.T_TERM_DSP, darkGray);
		tileColors.put(TileType.T_TERM_INT, darkGray);
		tileColors.put(TileType.T_TERM_INT_D, darkGray);
		tileColors.put(TileType.UL, black);
		tileColors.put(TileType.ULPPC_X0Y0_INT, black);
		tileColors.put(TileType.ULPPC_X1Y0_INT, black);
		tileColors.put(TileType.UR, black);
		tileColors.put(TileType.UR_LOWER, black);
		tileColors.put(TileType.UR_UPPER, black);
		tileColors.put(TileType.VBRK, darkBlue);
		tileColors.put(TileType.VFRAME, black);
		tileColors.put(TileType.VFRAME_NOMON, black);
		// Virtex 7, Kintex 7
		tileColors.put(TileType.BRAM_INT_INTERFACE_L, darkYellow);
		tileColors.put(TileType.BRAM_INT_INTERFACE_R, darkYellow);
		tileColors.put(TileType.BRAM_L, darkMagenta);
		tileColors.put(TileType.BRAM_L_FLY, black);
		tileColors.put(TileType.BRAM_R, darkMagenta);
		tileColors.put(TileType.BRKH_CLK, darkBlue);
		tileColors.put(TileType.BRKH_DSP_L, darkBlue);
		tileColors.put(TileType.BRKH_DSP_R, darkBlue);
		tileColors.put(TileType.BRKH_TERM_INT, darkBlue);
		tileColors.put(TileType.B_TERM_INT_NOUTURN, black);
		tileColors.put(TileType.B_TERM_INT_SLV, black);
		tileColors.put(TileType.CFG_CENTER_BOT, black);
		tileColors.put(TileType.CFG_CENTER_MID, black);
		tileColors.put(TileType.CFG_CENTER_MID_SLAVE, black);
		tileColors.put(TileType.CFG_CENTER_TOP, black);
		tileColors.put(TileType.CFG_CENTER_TOP_SLAVE, black);
		tileColors.put(TileType.CLBLL_L, new QColor(Qt.GlobalColor.blue));
		tileColors.put(TileType.CLBLL_R, new QColor(Qt.GlobalColor.blue));
		tileColors.put(TileType.CLBLM_L, new QColor(Qt.GlobalColor.blue));
		tileColors.put(TileType.CLBLM_R, new QColor(Qt.GlobalColor.blue));
		tileColors.put(TileType.CLK_BALI_REBUF, black);
		tileColors.put(TileType.CLK_BUFG_BOT_R, black);
		tileColors.put(TileType.CLK_BUFG_REBUF, black);
		tileColors.put(TileType.CLK_BUFG_TOP_R, black);
		tileColors.put(TileType.CLK_FEED, black);
		tileColors.put(TileType.CLK_HROW_BOT_R, black);
		tileColors.put(TileType.CLK_HROW_TOP_R, black);
		tileColors.put(TileType.CLK_PMV, black);
		tileColors.put(TileType.CLK_TERM, black);
		tileColors.put(TileType.CMT_FIFO_L, black);
		tileColors.put(TileType.CMT_FIFO_R, black);
		tileColors.put(TileType.CMT_PMV, black);
		tileColors.put(TileType.CMT_PMV_L, black);
		tileColors.put(TileType.CMT_TOP_L_LOWER_B, black);
		tileColors.put(TileType.CMT_TOP_L_LOWER_T, black);
		tileColors.put(TileType.CMT_TOP_L_UPPER_B, black);
		tileColors.put(TileType.CMT_TOP_L_UPPER_T, black);
		tileColors.put(TileType.CMT_TOP_R_LOWER_B, black);
		tileColors.put(TileType.CMT_TOP_R_LOWER_T, black);
		tileColors.put(TileType.CMT_TOP_R_UPPER_B, black);
		tileColors.put(TileType.CMT_TOP_R_UPPER_T, black);
		tileColors.put(TileType.DSP_L, darkCyan);
		tileColors.put(TileType.DSP_R, darkCyan);
		tileColors.put(TileType.GTX_CHANNEL_0, black);
		tileColors.put(TileType.GTX_CHANNEL_1, black);
		tileColors.put(TileType.GTX_CHANNEL_2, black);
		tileColors.put(TileType.GTX_CHANNEL_3, black);
		tileColors.put(TileType.GTX_COMMON, black);
		tileColors.put(TileType.GTX_INT_INTERFACE_L, black);
		tileColors.put(TileType.HCLK_CMT, cyan);
		tileColors.put(TileType.HCLK_CMT_L, cyan);
		tileColors.put(TileType.HCLK_DSP_L, cyan);
		tileColors.put(TileType.HCLK_DSP_R, cyan);
		tileColors.put(TileType.HCLK_FEEDTHRU_1, cyan);
		tileColors.put(TileType.HCLK_FEEDTHRU_2, cyan);
		tileColors.put(TileType.HCLK_FIFO_L, cyan);
		tileColors.put(TileType.HCLK_IOI3, cyan);
		tileColors.put(TileType.HCLK_L, cyan);
		tileColors.put(TileType.HCLK_L_BOT_UTURN, cyan);
		tileColors.put(TileType.HCLK_L_SLV, cyan);
		tileColors.put(TileType.HCLK_R, cyan);
		tileColors.put(TileType.HCLK_R_BOT_UTURN, cyan);
		tileColors.put(TileType.HCLK_R_SLV, cyan);
		tileColors.put(TileType.HCLK_TERM_GTX, cyan);
		tileColors.put(TileType.INT_FEEDTHRU_1, darkYellow);
		tileColors.put(TileType.INT_FEEDTHRU_2, darkYellow);
		tileColors.put(TileType.INT_INTERFACE_L, darkYellow);
		tileColors.put(TileType.INT_INTERFACE_R, darkYellow);
		tileColors.put(TileType.INT_L, darkYellow);
		tileColors.put(TileType.INT_L_SLV, darkYellow);
		tileColors.put(TileType.INT_L_SLV_FLY, darkYellow);
		tileColors.put(TileType.INT_R, darkYellow);
		tileColors.put(TileType.INT_R_SLV, darkYellow);
		tileColors.put(TileType.INT_R_SLV_FLY, darkYellow);
		tileColors.put(TileType.IO_INT_INTERFACE_L, darkYellow);
		tileColors.put(TileType.IO_INT_INTERFACE_R, darkYellow);
		tileColors.put(TileType.LIOB18, black);
		tileColors.put(TileType.LIOB18_SING, black);
		tileColors.put(TileType.LIOB33, black);
		tileColors.put(TileType.LIOB33_SING, black);
		tileColors.put(TileType.LIOI3, black);
		tileColors.put(TileType.LIOI3_SING, black);
		tileColors.put(TileType.LIOI3_TBYTESRC, black);
		tileColors.put(TileType.LIOI3_TBYTETERM, black);
		tileColors.put(TileType.LIOI_SING, black);
		tileColors.put(TileType.LIOI_TBYTESRC, black);
		tileColors.put(TileType.LIOI_TBYTETERM, black);
		tileColors.put(TileType.MONITOR_BOT, black);
		tileColors.put(TileType.MONITOR_BOT_FUJI2, black);
		tileColors.put(TileType.MONITOR_BOT_SLAVE, black);
		tileColors.put(TileType.MONITOR_MID, black);
		tileColors.put(TileType.MONITOR_MID_FUJI2, black);
		tileColors.put(TileType.MONITOR_TOP, black);
		tileColors.put(TileType.MONITOR_TOP_FUJI2, black);
		tileColors.put(TileType.PCIE_BOT, black);
		tileColors.put(TileType.PCIE_BOT_LEFT, black);
		tileColors.put(TileType.PCIE_INT_INTERFACE_LEFT_L, black);
		tileColors.put(TileType.PCIE_NULL, black);
		tileColors.put(TileType.PCIE_TOP_LEFT, black);
		tileColors.put(TileType.RIOB18, black);
		tileColors.put(TileType.RIOB18_SING, black);
		tileColors.put(TileType.RIOI_SING, black);
		tileColors.put(TileType.RIOI_TBYTESRC, black);
		tileColors.put(TileType.RIOI_TBYTETERM, black);
		tileColors.put(TileType.R_TERM_INT_GTX, black);
		tileColors.put(TileType.TERM_CMT, black);
		tileColors.put(TileType.T_TERM_INT_NOUTURN, black);
		tileColors.put(TileType.T_TERM_INT_SLV, black);
		tileColors.put(TileType.VBRK_EXT, black);
	}
}
